### ISSUE TITLE
Raycast range

### ISSUE THREAD

**Issue by KuzjaChe** [jhutchines/Unity-Object-Fade#1]
Thanks for sharing this code, simple and useful thing we needed right now!

The only small issue I noticed is that the raycast range is hardcoded to 50f units (FadeCheck.cs, line 20):
`if (Physics.Raycast(ray, out hit, 50f))`
 That can be not enough for some cameras. So I changed it to something like:
`if (Physics.Raycast(ray, out hit, Camera.main.farClipPlane))`

**Comment by jhutchines** [comment]
Hi KuzjaChe, glad you found this useful!

I've purposely left a few bits hardcoded in the scripts. My intention was to create something that could easily be plugged in and used by anyone, but I also wanted to encourage new programmers to read through and change parts to understand how it works.

I'm planning on creating more simple scripts like this, so if you have any ideas or recommendations then please let me know!
