### ISSUE TITLE
Multiple Fade

### ISSUE THREAD

**Issue by Tomiboo** [jhutchines/Unity-Object-Fade#2]
Hi there! I don't know if you're still updating this, but thanks for sharing this anyway. I've got a little problem here and I was wondering if you could help.

The Single fading mode works nicely, but I'm trying to fade a whole group of objects at the same time (object blocks the view > hide whole group), and I'm having trouble doing that. Multiple fading _kind of_ works, but I suspect that there's some bug in there.

I have three objects, side by side. They all have the ObjectFade script, with Multiple fading selected, and for each object's "Other Objects" index I've added the other two objects. But when I run the game, I'm getting some strange results. One object blocking the view makes them all fade like I intended, but another object blocking the view leaves one unfaded. The "Faded" checkbox also is sometimes checked for objects that are NOT faded, so I think that there may be something wrong with the part of the code that unfades the objects? 

Alternatively, would there be a way to only fade _siblings_ of a certain object in a hierarchy tree?

**Comment by jhutchines** [comment]
Hi Tomiboo,

I've replicated your issue both on the newest version and the version it was created on, and you're right. It is a bug!

The 'Multiple' type wasn't actually designed to be used in this fashion, so the objects are getting confused on what to listen to: Their own code or the other object's code that's telling it to turn transparent. I'll have a look into fixing this, but in the mean time you can get around by creating an empty game object, childing your three objects to it, and giving one of those objects the script with the 'Whole' type. That should function correctly in the way you are looking for (hiding all siblings if any sibling is hit by the raycast).

**Comment by Tomiboo** [comment]
First of all, thanks for the super quick reply! :) 

Nice to see that you're still interested in working on this. I will definitely check back again later if you ever get around to fixing that little bug. But your workaround solution should work just fine as well - in fact it even seems like a more elegant solution - so thanks for the advice!
